import React from "react";
import { useLanguage } from "../../context/LanguageContext";
import { T } from "../../data/nutricionStrings";

/**
 * For the small circular hero (180px / 360px retina) we serve an optimized
 * 360-square webp generated by `scripts/optimizar-imagenes.mjs`. Naming convention:
 *   /images/foo.webp  →  /images/foo-360.webp
 */
function smallVariant(src) {
  if (!src) return null;
  const dot = src.lastIndexOf(".");
  if (dot < 0) return src;
  return `${src.slice(0, dot)}-360.webp`;
}

const ProductHero = ({ producto }) => {
  const { language } = useLanguage();
  const t = (obj) => obj[language];
  const hasImage = Boolean(producto.imagen);
  const heroSrc = smallVariant(producto.imagen) || producto.imagen;

  return (
    <section
      style={{ padding: "8px 24px 28px", textAlign: "center" }}
      aria-labelledby="producto-nombre"
    >
      <div style={{ display: "flex", justifyContent: "center", marginBottom: 20 }}>
        <div
          style={{
            position: "relative",
            width: 180,
            height: 180,
            borderRadius: "50%",
            background: hasImage ? "#fffaf0" : producto.gradient,
            boxShadow:
              "inset -8px -12px 30px rgba(74,35,10,0.25), 0 20px 40px rgba(53,58,64,0.18)",
            overflow: "hidden",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {hasImage && (
            <img
              src={heroSrc}
              alt={t(producto.nombre)}
              width="360"
              height="360"
              fetchPriority="high"
              decoding="async"
              style={{
                width: "100%",
                height: "100%",
                objectFit: "cover",
                display: "block",
              }}
            />
          )}
          <div
            style={{
              position: "absolute",
              top: -10,
              right: -6,
              background: "#353a40",
              color: "#faf6f0",
              padding: "6px 14px",
              fontSize: 11,
              borderRadius: 2,
              transform: "rotate(8deg)",
              fontStyle: "italic",
              fontFamily: "var(--font-display)",
              letterSpacing: "0.15em",
              fontWeight: 600,
              boxShadow: "0 6px 16px -6px rgba(53,58,64,0.45)",
            }}
          >
            {t(T.desde)} {producto.desde}
          </div>
        </div>
      </div>

      <h1
        id="producto-nombre"
        style={{
          fontFamily: "var(--font-display)",
          fontSize: 34,
          lineHeight: 1.05,
          fontWeight: 500,
          margin: "0 0 10px",
          letterSpacing: "-0.025em",
          color: "#353a40",
        }}
      >
        {t(producto.nombre)}
      </h1>
      <p
        style={{
          fontSize: 11,
          textTransform: "uppercase",
          letterSpacing: "0.2em",
          color: "#8a7560",
          margin: "0 0 16px",
          fontWeight: 500,
        }}
      >
        {t(producto.tagline)}
      </p>
      <p
        style={{
          fontSize: 14.5,
          lineHeight: 1.55,
          color: "#5a5248",
          margin: "0 auto",
          maxWidth: 320,
          fontStyle: "italic",
        }}
      >
        {t(producto.descripcion)}
      </p>
    </section>
  );
};

export default ProductHero;
